# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('lodging_offer_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Hostel', 'Hostal'), ('Student Residence', 'Residencia estudiantil'), ('Accommodation with local family', 'Acomodación con familia local'), ('House or apartment to share with other visitors', 'Casa o apartamento para compartir con otros huéspedes'), ('House or private apartment', 'Casa o apartamento privado')], max_length=255, verbose_name='Lodging offer type')),
                ('stars', models.CharField(choices=[('1 star', '1 estrella'), ('2 stars', '2 estrellas'), ('3 stars', '3 estrellas'), ('4 stars', '4 estrellas'), ('5 stars', '5 estrellas')], max_length=255, verbose_name='Stars numbers')),
                ('check_in', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Check In')),
                ('check_out', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Check Out')),
                ('room_type_offered', models.CharField(choices=[('All property', 'Toda la propiedad'), ('Private Room', 'Habitación privada'), ('Shared Room', 'Habitación compartida')], max_length=255, verbose_name='Room Type Offered')),
                ('number_guest_room_type', models.CharField(choices=[('For 1 guest', 'Para 1 huésped'), ('For 2 guests', 'Para 2 huéspedes'), ('3 guests', 'Para 3 huéspedes'), ('4 guests', 'Para 4 huéspedes'), ('5 guests', 'Para 5 huéspedes'), ('6 guests', 'Para 6 huéspedes'), ('7 guests', 'Para 7 huéspedes'), ('8 guests', 'Para 8 huéspedes'), ('9 guests', 'Para 9 huéspedes'), ('10 guests', 'Para 10 huéspedes')], max_length=255, verbose_name='Número de huéspedes en habitación')),
                ('bed_type', models.CharField(choices=[('Single bed', 'Cama individual'), ('Double bed', 'Cama doble')], max_length=10, verbose_name='Tipo de cama')),
                ('bathroom', models.CharField(choices=[('Private bathroom', 'Baño privado'), ('Shared bathroom', 'Baño compartido')], max_length=20, verbose_name='Bathroom')),
                ('photographies', models.ImageField(blank=True, null=True, upload_to='hosting-host-photos', verbose_name='Photographies')),
                ('room_value', models.CharField(max_length=128, verbose_name='Precio')),
                ('additional_description', models.TextField(verbose_name='Descripción adicional')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('featured_amenities', models.ManyToManyField(help_text='What amenities do you offer?', to='host_information.FeaturesAmenities', verbose_name='Comodidades destacadas')),
                ('offered_services', models.ManyToManyField(help_text='What services do you offer?', related_name='lodgingoffers', to='host_information.OfferedServices', verbose_name='Servicios ofrecidos')),
                ('room_information', models.ManyToManyField(help_text='Room caracteristics', related_name='lodgingoffers', to='host_information.RoomInformation', verbose_name='Características de la habitación')),
            ],
        ),
    ]
