# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-05 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import hosts.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('host_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255, verbose_name='Título de la oferta')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pais')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('lodging_offer_type_org', models.CharField(blank=True, choices=[(' ', ' '), ('Hotel', 'Hotel'), ('Hostal', 'Hostal'), ('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspedes', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], max_length=255, null=True, verbose_name='Tipo de oferta de alojamiento')),
                ('lodging_offer_type', models.CharField(blank=True, choices=[(' ', ' '), ('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspedes', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], max_length=255, null=True, verbose_name='Tipo de oferta de alojamiento')),
                ('stars', models.CharField(blank=True, choices=[(' ', ' '), ('1 estrella', '1 estrella'), ('2 estrellas', '2 estrellas'), ('3 estrellas', '3 estrellas'), ('4 estrellas', '4 estrellas'), ('5 estrellas', '5 estrellas')], max_length=255, null=True, verbose_name='Número de estrellas')),
                ('check_in', models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Check In')),
                ('check_out', models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Check Out')),
                ('room_type_offered', models.CharField(choices=[('Toda la propiedad', 'Toda la propiedad'), ('Habitación privada', 'Habitación privada'), ('Habitación compartida', 'Habitación compartida')], max_length=255, verbose_name='Tipo de habitación ofrecida')),
                ('number_guest_room_type', models.CharField(choices=[('Para 1 huésped', 'Para 1 huésped'), ('Para 2 huéspedes', 'Para 2 huéspedes'), ('Para 3 huéspede', 'Para 3 huéspedes'), ('Para 4 huéspedes', 'Para 4 huéspedes'), ('Para 5 huéspedes', 'Para 5 huéspedes'), ('Para 6 huéspedes', 'Para 6 huéspedes'), ('Para 7 huéspedes', 'Para 7 huéspedes'), ('Para 8 huéspedes', 'Para 8 huéspedes')], max_length=255, verbose_name='Número de huéspedes en habitación')),
                ('bed_type', models.CharField(choices=[('Cama individual', 'Cama individual'), ('Cama doble', 'Cama doble')], max_length=20, verbose_name='Tipo de cama')),
                ('photo', models.ImageField(help_text='Esta imagen acompañará tu oferta en los resultados de búsquedas', upload_to=hosts.models.get_lodging_image_search_path, verbose_name='Fotografía')),
                ('room_value', models.CharField(help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio')),
                ('additional_description', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_taked', models.BooleanField(default=False, verbose_name='Oferta tomada')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Oferta promovida')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('featured_amenities', models.ManyToManyField(help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', to='host_information.FeaturesAmenities', verbose_name='Comodidades destacadas')),
                ('offered_services', models.ManyToManyField(help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', related_name='lodgingoffers', to='host_information.OfferedServices', verbose_name='Servicios ofrecidos')),
                ('room_information', models.ManyToManyField(help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', related_name='lodgingoffers', to='host_information.RoomInformation', verbose_name='Características de la habitación')),
            ],
            options={
                'ordering': ['-is_paid', '-pub_date', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='LodgingOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hosts.models.get_image_filename, verbose_name='Imagen')),
                ('lodging_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgingofferimage', to='hosts.LodgingOffer')),
            ],
        ),
        migrations.CreateModel(
            name='StudiesOffert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255, verbose_name='Título de la oferta')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='País')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('maximum_quota', models.PositiveSmallIntegerField(verbose_name='Cupo máximo de estudiantes')),
                ('studies_type_offered', models.CharField(choices=[('Estudios de educación contínua', 'Estudios de educación contínua'), ('Técnica', 'Técnica'), ('Tecnología', 'Tecnología'), ('Pregrado', 'Pregrado'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Movilidad académica', 'Movilidad académica')], max_length=255, verbose_name='Tipo de estudios ofertados')),
                ('academic_mobility_programs', models.CharField(choices=[('Semestre académico', 'Semestre académico'), ('Investigación', 'Investigación'), ('Rotaciones o prácticas', 'Rotaciones o prácticas'), ('Escuela de verano', 'Escuela de verano')], max_length=255, verbose_name='Programas de movilidad académica')),
                ('duration', models.CharField(max_length=255, verbose_name='Duración')),
                ('intensity', models.CharField(max_length=255, verbose_name='Intensidad')),
                ('modality', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial')], max_length=20, verbose_name='Modalidad')),
                ('studies_value', models.CharField(help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio')),
                ('additional_description', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('photo', models.ImageField(help_text='Esta imagen acompañará tu oferta en los resultados de búsquedas', upload_to=hosts.models.get_image_search_path, verbose_name='Fotografía')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_taked', models.BooleanField(default=False, verbose_name='Oferta tomada')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Oferta promovida')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('knowledge_topics', taggit.managers.TaggableManager(help_text='Una lista de temáticas separada por comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tópicos de conocimiento')),
            ],
            options={
                'ordering': ['-is_paid', '-pub_date', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='StudyOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hosts.models.get_image_path, verbose_name='Seleccionar imagen')),
                ('study_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadsstudyoffer', to='hosts.StudiesOffert')),
            ],
        ),
    ]
