# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiesoffert',
            name='academic_mobility_programs',
            field=models.CharField(blank=True, choices=[('Semestre académico', 'Semestre académico'), ('Investigación', 'Investigación'), ('Rotaciones o prácticas', 'Rotaciones o prácticas'), ('Escuela de verano', 'Escuela de verano')], max_length=255, null=True, verbose_name='Programas de movilidad académica'),
        ),
    ]
