# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='image',
            field=models.ImageField(help_text='Esta imagen acompañará tu oferta en los resultados de búsquedas', upload_to=hosts.models.get_lodging_image_search_path, verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='photo',
            field=models.ImageField(help_text='Esta imagen acompañará tu oferta en los resultados de búsquedas', upload_to=hosts.models.get_image_search_path, verbose_name='Fotografía'),
        ),
    ]
