# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='room_value',
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='monthly_price',
            field=models.CharField(default=1, help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio mensual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='room_night_value',
            field=models.CharField(default=1, help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio por noche'),
            preserve_default=False,
        ),
    ]
