# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-03 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='lodging_offer_type_org',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hostal', 'Hostal'), ('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspedes', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], default=1, max_length=255, verbose_name='Tipo de oferta de alojamiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='is_taked',
            field=models.BooleanField(default=False, verbose_name='Oferta tomada'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='lodging_offer_type',
            field=models.CharField(choices=[('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspedes', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], max_length=255, verbose_name='Tipo de oferta de alojamiento'),
        ),
    ]
