# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-22 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20180121_2328'),
        # ('hosts', '0002_lodgingoffer_is_paid'),
    ]

    operations = [
    ]
