# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-21 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_lodgingoffer_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodgingoffer',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='studiesoffert',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Oferta promovida'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='is_taked',
            field=models.BooleanField(default=False, verbose_name='Oferta tomada'),
        ),
    ]
