# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-02 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20171202_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='image',
        ),
    ]
