# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20180325_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='location_zone',
            field=models.CharField(default=1, help_text='Precio en pesos colombianos', max_length=128, verbose_name='Zona/Barrio'),
            preserve_default=False,
        ),
    ]
