# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20171028_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='bathroom',
            field=models.CharField(choices=[('Baño privado', 'Baño privado'), ('Baño compartido', 'Baño compartido')], max_length=20, verbose_name='Baño'),
        ),
    ]
