# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20180419_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_in',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_out',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='lodging_offer_type',
            field=models.CharField(blank=True, choices=[('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspedes', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], max_length=255, null=True, verbose_name='Tipo de oferta de alojamiento'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='lodging_offer_type_org',
            field=models.CharField(blank=True, choices=[('Hotel', 'Hotel'), ('Hostal', 'Hostal'), ('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspedes', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], max_length=255, null=True, verbose_name='Tipo de oferta de alojamiento'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='monthly_price',
            field=models.CharField(blank=True, help_text='Precio en pesos colombianos', max_length=128, null=True, verbose_name='Precio mensual'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='number_guest_room_type',
            field=models.CharField(choices=[('Para 1 huésped', 'Para 1 huésped'), ('Para 2 huéspedes', 'Para 2 huéspedes'), ('Para 3 huéspedes', 'Para 3 huéspedes'), ('Para 4 huéspedes', 'Para 4 huéspedes'), ('Para 5 huéspedes', 'Para 5 huéspedes'), ('Para 6 huéspedes', 'Para 6 huéspedes'), ('Para 7 huéspedes', 'Para 7 huéspedes'), ('Para 8 huéspedes', 'Para 8 huéspedes')], max_length=255, verbose_name='Número de huéspedes en habitación'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_night_value',
            field=models.CharField(blank=True, help_text='Precio en pesos colombianos', max_length=128, null=True, verbose_name='Precio por noche'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='stars',
            field=models.CharField(blank=True, choices=[('1 estrella', '1 estrella'), ('2 estrellas', '2 estrellas'), ('3 estrellas', '3 estrellas'), ('4 estrellas', '4 estrellas'), ('5 estrellas', '5 estrellas')], max_length=255, null=True, verbose_name='Número de estrellas'),
        ),
    ]
