# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-03 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_remove_lodgingoffer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='lodging_offer_type_person',
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='image',
            field=models.ImageField(default=1, help_text='Esta imagen acompañará tu oferta en los resultados de búsquedas', upload_to=hosts.models.get_lodging_image_search_path, verbose_name='Fotografía'),
            preserve_default=False,
        ),
    ]
