# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20180121_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiesoffert',
            options={'ordering': ['-is_paid', '-pub_date']},
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
