# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_delete_studiestypeoffered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='bathroom',
            field=models.CharField(choices=[('Private bathroom', 'Baño privado'), ('Shared bathroom', 'Baño compartido')], max_length=20, verbose_name='Baño'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_in',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>MM-DD-YYYY</em>.', null=True, verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_out',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>MM-DD-YYYY</em>.', null=True, verbose_name='Check Out'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='featured_amenities',
            field=models.ManyToManyField(help_text='Mantenga presionado "Control" o "Command" en un Mac, para seleccionar más de una opción.', to='host_information.FeaturesAmenities', verbose_name='Comodidades destacadas'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='lodging_offer_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hostel', 'Hostal'), ('Student Residence', 'Residencia estudiantil'), ('Accommodation with local family', 'Acomodación con familia local'), ('House or apartment to share with other visitors', 'Casa o apartamento para compartir con otros huéspedes'), ('House or private apartment', 'Casa o apartamento privado')], max_length=255, verbose_name='Tipo de oferta de alojamiento'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='offered_services',
            field=models.ManyToManyField(help_text='Mantenga presionado "Control" o "Command" en un Mac, para seleccionar más de una opción.', related_name='lodgingoffers', to='host_information.OfferedServices', verbose_name='Servicios ofrecidos'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='photographies',
            field=models.ImageField(default=1, upload_to='hosting-host-photos', verbose_name='Photographies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_information',
            field=models.ManyToManyField(help_text='Mantenga presionado "Control" o "Command" en un Mac, para seleccionar más de una opción.', related_name='lodgingoffers', to='host_information.RoomInformation', verbose_name='Características de la habitación'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_type_offered',
            field=models.CharField(choices=[('All property', 'Toda la propiedad'), ('Private Room', 'Habitación privada'), ('Shared Room', 'Habitación compartida')], max_length=255, verbose_name='Tipo de habitación ofrecida'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='photo',
            field=models.ImageField(default=1, upload_to='study-host-offert-photos', verbose_name='Photography'),
            preserve_default=False,
        ),
    ]
