# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-24 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20180215_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='bathroom',
        ),
    ]
