# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_lodgingoffer_location_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='location_zone',
            field=models.CharField(help_text='Sector por donde está ubicada la oferta', max_length=128, verbose_name='Zona/Barrio'),
        ),
    ]
