# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-28 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20180505_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='discounts',
            field=models.CharField(default=1, max_length=20, verbose_name='Descuentos'),
            preserve_default=False,
        ),
    ]
