# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20180121_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiesoffert',
            options={'ordering': ['-pub_date', '-updated']},
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
