# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20170923_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='featured_amenities',
            field=models.ManyToManyField(help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', to='host_information.FeaturesAmenities', verbose_name='Comodidades destacadas'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='offered_services',
            field=models.ManyToManyField(help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', related_name='lodgingoffers', to='host_information.OfferedServices', verbose_name='Servicios ofrecidos'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_information',
            field=models.ManyToManyField(help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', related_name='lodgingoffers', to='host_information.RoomInformation', verbose_name='Características de la habitación'),
        ),
    ]
