# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-28 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_lodgingoffer_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_in',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Disponibilidad desde:'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_out',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Disponibilidad hasta:'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='number_guest_room_type',
            field=models.CharField(max_length=255, verbose_name='Número de huéspedes en habitación'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_type_offered',
            field=models.CharField(choices=[('Privada', 'Privada'), ('Compartida', 'Compartida')], max_length=255, verbose_name='Tipo de habitación ofrecida'),
        ),
    ]
