# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-12 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20171203_0220'),
        ('hosts', '0004_auto_20171203_0139'),
    ]

    operations = [
    ]
