# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-12 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_merge_20180112_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodgingoffer',
            old_name='image',
            new_name='photo',
        ),
    ]
