# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20170930_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='bathroom',
            field=models.CharField(choices=[('Baño privado', 'Baño privado'), ('Baño compartid', 'Baño compartido')], max_length=20, verbose_name='Baño'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='bed_type',
            field=models.CharField(choices=[('Cama individual', 'Cama individual'), ('Cama doble', 'Cama doble')], max_length=10, verbose_name='Tipo de cama'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_in',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Check In'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='check_out',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Check Out'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='lodging_offer_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hostal', 'Hostal'), ('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspede', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], max_length=255, verbose_name='Tipo de oferta de alojamiento'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='number_guest_room_type',
            field=models.CharField(choices=[('Para 1 huésped', 'Para 1 huésped'), ('Para 2 huéspedes', 'Para 2 huéspedes'), ('Para 3 huéspede', 'Para 3 huéspedes'), ('Para 4 huéspedes', 'Para 4 huéspedes'), ('Para 5 huéspedes', 'Para 5 huéspedes'), ('Para 6 huéspedes', 'Para 6 huéspedes'), ('Para 7 huéspedes', 'Para 7 huéspedes'), ('Para 8 huéspedes', 'Para 8 huéspedes'), ('Para 9 huéspedes', 'Para 9 huéspedes'), ('Para 10 huéspedes', 'Para 10 huéspedes')], max_length=255, verbose_name='Número de huéspedes en habitación'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='photographies',
            field=models.ImageField(upload_to='hosting-host-photos', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_type_offered',
            field=models.CharField(choices=[('Toda la propiedad', 'Toda la propiedad'), ('Habitación privada', 'Habitación privada'), ('Habitación compartida', 'Habitación compartida')], max_length=255, verbose_name='Tipo de habitación ofrecida'),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='stars',
            field=models.CharField(choices=[('1 estrella', '1 estrella'), ('2 estrellas', '2 estrellas'), ('3 estrellas', '3 estrellas'), ('4 estrellas', '4 estrellas'), ('5 estrellas', '5 estrellas')], max_length=255, verbose_name='Número de estrellas'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='academic_mobility_programs',
            field=models.CharField(choices=[('Semestre académico', 'Semestre académico'), ('Investigación', 'Investigación'), ('Rotaciones o prácticas', 'Rotaciones o prácticas'), ('Escuela de verano', 'Escuela de verano')], max_length=255, verbose_name='Programas de movilidad académica'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='additional_description',
            field=models.TextField(verbose_name='Descripción adicional'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='institute_character',
            field=models.CharField(choices=[('Privada', 'Privada'), ('Pública', 'Pública'), ('Privada - Pública', 'Privada - Pública')], max_length=20, verbose_name='Caracter de la institución'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='modality',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial')], max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='photo',
            field=models.ImageField(upload_to='study-host-offert-photos', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='studies_type_offered',
            field=models.CharField(choices=[('Estudios de educación contínua', 'Estudios de educación contínua'), ('Técnica', 'Tecnología'), ('Tecnología', 'Técnica'), ('Profesional', 'Profesional'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Movilidad académica', 'Movilidad académica')], max_length=255, verbose_name='Tipo de estudios ofertados'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='studies_value',
            field=models.CharField(max_length=128, verbose_name='Precio'),
        ),
    ]
