# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_auto_20171002_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='bed_type',
            field=models.CharField(choices=[('Cama individual', 'Cama individual'), ('Cama doble', 'Cama doble')], max_length=20, verbose_name='Tipo de cama'),
        ),
    ]
