# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-28 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_auto_20181028_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiesoffert',
            name='academic_mobility_programs',
        ),
        migrations.RemoveField(
            model_name='studiesoffert',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='studiesoffert',
            name='knowledge_topics',
        ),
        migrations.RemoveField(
            model_name='studiesoffert',
            name='maximum_quota',
        ),
        migrations.RemoveField(
            model_name='studiesoffert',
            name='studies_type_offered',
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='finish_date',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha de terminación:'),
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='formation_type_offered',
            field=models.CharField(choices=[('Curso corto', 'Curso corto'), ('Seminario', 'Seminario'), ('Diplomado', 'Diplomado'), ('Taller', 'Taller'), ('Técnica', 'Técnica')], default=1, max_length=255, verbose_name='Tipo de formación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='start_date',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha de inicio:'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='modality',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('Semi-presencial', 'Semi-presencial')], max_length=20, verbose_name='Modalidad'),
        ),
    ]
