# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-30 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_auto_20181030_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiesoffert',
            name='is_taked',
        ),
        migrations.AddField(
            model_name='studiesoffert',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Oferta finalizada'),
        ),
    ]
