# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-07 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_auto_20181030_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiesoffert',
            name='discounts',
            field=models.CharField(help_text='Descuentos', max_length=128, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='organizers',
            field=models.ImageField(blank=True, help_text='Logos de los organizadores', null=True, upload_to=hosts.models.get_image_search_path, verbose_name='Organizadores'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='sponsors',
            field=models.ImageField(blank=True, help_text='Logos de los patrocinadores', null=True, upload_to=hosts.models.get_image_search_path, verbose_name='Patrocinadores'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='status',
            field=models.CharField(choices=[('Cupos disponibles', 'Cupos disponibles'), ('Cupos agotados', 'Cupos agotados'), ('Cancelada', 'Cancelada')], max_length=255, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='support',
            field=models.ImageField(blank=True, help_text='Logos de quien apoya', null=True, upload_to=hosts.models.get_image_search_path, verbose_name='Apoya'),
        ),
    ]
