# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_auto_20171003_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingoffer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='lodging_offer_type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hostal', 'Hostal'), ('Residencia estudiantil', 'Residencia estudiantil'), ('Acomodación con familia local', 'Acomodación con familia local'), ('Casa o apartamento para compartir con otros huéspedes', 'Casa o apartamento para compartir con otros huéspedes'), ('Casa o apartamento privado', 'Casa o apartamento privado')], max_length=255, verbose_name='Tipo de oferta de alojamiento'),
        ),
    ]
