# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-12 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_auto_20171009_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodgingoffer',
            old_name='photographies',
            new_name='image',
        ),
    ]
