# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_auto_20171012_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingoffer',
            name='room_value',
            field=models.CharField(help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='studies_type_offered',
            field=models.CharField(choices=[('Estudios de educación contínua', 'Estudios de educación contínua'), ('Técnica', 'Técnica'), ('Tecnología', 'Tecnología'), ('Pregrado', 'Pregrado'), ('Especialización', 'Especialización'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Movilidad académica', 'Movilidad académica')], max_length=255, verbose_name='Tipo de estudios ofertados'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='studies_value',
            field=models.CharField(help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio'),
        ),
    ]
