# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_auto_20171013_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
