# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0013_studiesoffert_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='is_taked',
            field=models.BooleanField(default=False, help_text='Indica si esta oferta ya fue tomada por un usuario. Si se selecciona, no aparecerá en los resultadosde búsquedas. Des-seleccionéla en lugar de eliminar la oferta', verbose_name='Oferta tomada'),
        ),
    ]
