# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-17 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_lodgingoffer_is_taked'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers/lodging/')),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lodgingoffer',
            name='image',
        ),
        migrations.AlterField(
            model_name='lodgingoffer',
            name='is_taked',
            field=models.BooleanField(default=False, help_text='Indica si esta oferta ya fue tomada por un usuario.  <br /> Este campo es solo para uso de actualización de una oferta cuando ya ha habido un acuerdo por ella. Si se selecciona, no aparecerá en los resultados de búsquedas. <br /> Des-seleccionéla en lugar de eliminar la oferta', verbose_name='Oferta tomada'),
        ),
        migrations.AlterField(
            model_name='studiesoffert',
            name='is_taked',
            field=models.BooleanField(default=False, help_text='Indica si esta oferta ya fue tomada por un usuario.  <br /> Este campo es solo para uso de actualización de una oferta cuando ya ha habido un acuerdo por ella. Si se selecciona, no aparecerá en los resultados de búsquedas. <br /> Des-seleccionéla en lugar de eliminar la oferta', verbose_name='Oferta tomada'),
        ),
        migrations.AddField(
            model_name='lodgingofferimage',
            name='lodging_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.LodgingOffer'),
        ),
    ]
