# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0016_auto_20171017_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingofferimage',
            name='lodging_offer',
        ),
        migrations.AddField(
            model_name='lodgingoffer',
            name='image',
            field=models.ImageField(default=1, upload_to='hosting-host-photos', verbose_name='Fotografía'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LodgingOfferImage',
        ),
    ]
