# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_auto_20171019_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hosts.models.get_image_filename, verbose_name='Imagen')),
                ('lodging_offer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hosts.LodgingOffer')),
            ],
        ),
    ]
