# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0019_auto_20171019_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadStudyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hosts.models.get_image_path)),
                ('study_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadsstudyoffer', to='hosts.StudiesOffert')),
            ],
        ),
        migrations.AlterField(
            model_name='lodgingofferimage',
            name='lodging_offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hosts.LodgingOffer'),
        ),
    ]
