# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0021_auto_20171023_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadstudyoffer',
            name='image',
            field=models.ImageField(upload_to=hosts.models.get_image_path),
        ),
    ]
