# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0028_auto_20171024_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadstudyoffer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uploadstudyoffer',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadstudyoffer',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadstudyoffer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
