# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0029_auto_20171024_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadstudyoffer',
            options={'ordering': ['-start_date', '-end_date']},
        ),
        migrations.AddField(
            model_name='uploadstudyoffer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadstudyoffer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
