# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0030_auto_20171024_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadstudyoffer',
            options={'ordering': ['order', '-start_date', '-end_date']},
        ),
        migrations.AddField(
            model_name='uploadstudyoffer',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadstudyoffer',
            name='active',
            field=models.BooleanField(default=True, help_text='Indica si una imagen de oferta esta habilitada o disponible', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='uploadstudyoffer',
            name='featured',
            field=models.BooleanField(default=False, help_text='Indica si la imagen aparecera en el carrusel', verbose_name='Destacada'),
        ),
        migrations.AlterField(
            model_name='uploadstudyoffer',
            name='image',
            field=models.ImageField(upload_to=hosts.models.get_image_path, verbose_name='Seleccionar imagen'),
        ),
    ]
