# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0031_auto_20171024_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadstudyoffer',
            name='end_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadstudyoffer',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
