# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0032_auto_20171024_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiesoffert',
            name='photo',
        ),
    ]
