# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0035_auto_20171025_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodgingofferimage',
            old_name='thumbnail_image',
            new_name='image',
        ),
    ]
