# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0036_auto_20171025_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiesoffert',
            name='intensity',
            field=models.CharField(default=1, max_length=255, verbose_name='Intensidad'),
            preserve_default=False,
        ),
    ]
