# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0037_studiesoffert_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiesoffert',
            name='institute_character',
        ),
    ]
