# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 21:00
from __future__ import unicode_literals

import daily_life.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLifeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ad_title', models.CharField(max_length=255, verbose_name='Título de la oferta')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pais')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('offer_type', models.CharField(choices=[('Transporte', 'Transporte'), ('Salud y bienestar', 'Salud y bienestar'), ('Deporte', 'Deporte'), ('Compras', 'Compras'), ('Gastronomía', 'Gastronomía'), ('Turismo', 'Turismo'), ('Vida nocturna', 'Vida nocturna'), ('Eventos y espectáculos', 'Eventos y espectáculos'), ('Actividades al aire libre', 'Actividades al aire libre'), ('Otros', 'Otros')], max_length=100, verbose_name='Tipo de oferta')),
                ('photo', models.ImageField(help_text='Esta imagen acompañará tu oferta en los resultados de búsquedas', upload_to=daily_life.models.get_daily_life_image_path, verbose_name='Fotografía')),
                ('address', models.CharField(help_text='Precio en pesos colombianos', max_length=128, verbose_name='Dirección')),
                ('price', models.CharField(help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio')),
                ('additional_description', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('is_taked', models.BooleanField(default=False, verbose_name='Oferta tomada')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Oferta promovida')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_paid', '-created', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='DailyLifeOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=daily_life.models.get_image_filename, verbose_name='Imagen')),
                ('daily_life_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailylifeofferimage', to='daily_life.DailyLifeOffer')),
            ],
        ),
    ]
