# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-27 09:51
from __future__ import unicode_literals

import daily_life.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_life', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurshipOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=daily_life.models.get_image_filename, verbose_name='Imagen')),
                ('daily_life_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailylifeofferimage', to='daily_life.DailyLifeOffer')),
            ],
        ),
    ]
