# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-27 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_life', '0002_entrepreneurshipofferimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrepreneurshipOfferImage',
            new_name='DailyLifeOfferImage',
        ),
    ]
