# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-15 13:38
from __future__ import unicode_literals

import carousel_offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalOfferSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=carousel_offers.models.educational_slider_upload)),
                ('order', models.IntegerField(default=0)),
                ('url_link', models.CharField(blank=True, max_length=250, null=True)),
                ('header_text', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.CharField(blank=True, max_length=120, null=True)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', '-start_date', '-end_date'],
            },
        ),
    ]
