# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-17 16:33
from __future__ import unicode_literals

import carousel_offers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carousel_offers', '0002_educationalofferslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalofferslider',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='educationalofferslider',
            name='title',
            field=models.CharField(default=1, max_length=120, verbose_name='Ingrese el nombre de quien pauta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalofferslider',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgingoffercarousel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lodgingoffercarousel',
            name='title',
            field=models.CharField(default=1, max_length=120, verbose_name='Ingrese el nombre de quien pauta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lodgingoffercarousel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='active',
            field=models.BooleanField(default=False, help_text='Indica si el anuncio estara activo o no en la pagina de busquedas de educacion'),
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='end_date',
            field=models.DateField(blank=True, help_text='Indica hasta que fecha el anuncio estara en la pagina de busquedas de educacion', null=True, verbose_name='Fecha de finalizacion del anuncio'),
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='header_text',
            field=models.CharField(blank=True, help_text='Opcional', max_length=120, null=True, verbose_name='Ingrese un encabezado para el banner'),
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='image',
            field=models.ImageField(upload_to=carousel_offers.models.educational_slider_upload, verbose_name='Imagen a aparecer en el carrusel'),
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='order',
            field=models.IntegerField(default=0, help_text='Ingrese un numero', verbose_name='Ingrese el orden en que desea que aparezca la imagen'),
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='start_date',
            field=models.DateField(blank=True, help_text='Indica desde que fecha el anuncio empezara a aparecer en la pagina de busquedas de educacion', null=True, verbose_name='Fecha de inicio del anuncio'),
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='text',
            field=models.CharField(blank=True, help_text='Opcional', max_length=120, null=True, verbose_name='Ingrese un caption para el banner'),
        ),
        migrations.AlterField(
            model_name='educationalofferslider',
            name='url_link',
            field=models.CharField(blank=True, help_text='Opcional', max_length=250, null=True, verbose_name='Ingrese un enlace promocional'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='active',
            field=models.BooleanField(default=False, help_text='Indica si el anuncio estara activo o no en la pagina de busquedas de alojamiento'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='end_date',
            field=models.DateField(blank=True, help_text='Indica hasta que fecha el anuncio estara en la pagina de busquedas de alojamiento', null=True, verbose_name='Fecha de finalizacion del anuncio'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='header_text',
            field=models.CharField(blank=True, help_text='Opcional', max_length=120, null=True, verbose_name='Ingrese un encabezado para el banner'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='image',
            field=models.ImageField(upload_to=carousel_offers.models.lodging_slider_upload, verbose_name='Imagen a aparecer en el carrusel'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='order',
            field=models.IntegerField(default=0, help_text='Ingrese un numero', verbose_name='Ingrese el orden en que desea que aparezca la imagen'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='start_date',
            field=models.DateField(blank=True, help_text='Indica desde que fecha el anuncio empezara a aparecer en la pagina de busquedas de alojamiento', null=True, verbose_name='Fecha de inicio del anuncio'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='text',
            field=models.CharField(blank=True, help_text='Opcional', max_length=120, null=True, verbose_name='Ingrese un caption para el banner'),
        ),
        migrations.AlterField(
            model_name='lodgingoffercarousel',
            name='url_link',
            field=models.CharField(blank=True, help_text='Opcional', max_length=250, null=True, verbose_name='Ingrese un enlace promocional'),
        ),
    ]
