# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 21:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid email address.', 'invalid')])),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.', 'invalid')], verbose_name='username')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('enterprise_name', models.CharField(blank=True, max_length=100, verbose_name='enterprise name')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Gender')),
                ('country_of_origin', django_countries.fields.CountryField(max_length=2)),
                ('city_of_origin', models.CharField(max_length=255)),
                ('country_current_residence', django_countries.fields.CountryField(max_length=2)),
                ('city_current_residence', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Please use the following format: <em>+Country Code-Number</em>.', max_length=128)),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('bio', models.CharField(blank=True, default='', max_length=140)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Photo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('user_type', models.CharField(choices=[('P', 'Persona'), ('E', 'Empresa')], default=False, max_length=10, verbose_name='Tipo de Usuario')),
                ('is_student', models.BooleanField(default=False, help_text='Student profile', verbose_name='Estudiante')),
                ('is_professor', models.BooleanField(default=False, help_text='Professor profile', verbose_name='Profesor')),
                ('is_executive', models.BooleanField(default=False, help_text='Executive profile', verbose_name='Ejecutivo/Emprendedor')),
                ('is_study_host', models.BooleanField(default=False, help_text='Study host profile', verbose_name='Anfitrion de estudio')),
                ('is_innovation_host', models.BooleanField(default=False, help_text='Innovation host profile', verbose_name='Anfitrión de innovación')),
                ('is_hosting_host', models.BooleanField(default=False, help_text='Hosting host profile', verbose_name='Anfitrión de alojamiento')),
                ('is_entertainment_host', models.BooleanField(default=False, help_text='Entertainment host profile', verbose_name='Anfitrión de entretenimiento')),
                ('is_other_services_host', models.BooleanField(default=False, help_text='Other services host profile', verbose_name='Anfitrión de otros servicios')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios en la plataforma',
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='EntertainmentHostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de anfitriones de entretenimiento',
            },
        ),
        migrations.CreateModel(
            name='ExecutiveProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('enterprise_name', models.CharField(max_length=255, verbose_name='Compañía con la cual esta vinculado')),
                ('innovation_topics_choice', models.CharField(max_length=255, verbose_name='Areas de innovación de su elección')),
                ('educational_titles', models.CharField(max_length=255, verbose_name='Títulos educativos')),
                ('complete_studies_school', models.CharField(max_length=255, verbose_name='Institución donde terminó sus estudios anteriores')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de ejecutivos',
            },
        ),
        migrations.CreateModel(
            name='HostingHostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('additional_description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de anfitriones de hospedaje',
            },
        ),
        migrations.CreateModel(
            name='InnovationHostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de anfitriones de innovación',
            },
        ),
        migrations.CreateModel(
            name='OtherServicesHostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de anfitriones de servicios varios',
            },
        ),
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('occupation', models.CharField(max_length=255)),
                ('origin_education_school', models.CharField(max_length=128, verbose_name='Institución de educación de origen')),
                ('current_education_school', models.CharField(max_length=128, verbose_name='Institución de educación a la cual esta vinculada su actual residencia')),
                ('educational_titles', models.CharField(max_length=255)),
                ('complete_studies_school', models.CharField(max_length=255, verbose_name='Institución donde terminó sus estudios anteriores')),
                ('knowledge_topics_choice', models.CharField(max_length=255, verbose_name='Areas de conocimiento de su elección')),
                ('research_groups', models.CharField(max_length=255, verbose_name='Grupos de Investigación a los que pertenece')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de profesores',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('origin_education_school', models.CharField(max_length=128, verbose_name='Institución de educación origen')),
                ('current_education_school', models.CharField(max_length=128, verbose_name='Institución de educación a la cual esta vinculada su actual residencia')),
                ('extra_occupation', models.CharField(max_length=128, verbose_name='Ocupación Extra')),
                ('educational_titles', models.CharField(max_length=255, verbose_name='Titulos Educativos')),
                ('complete_studies_school', models.CharField(max_length=255, verbose_name='Institución en donde completó sus estudios anteriores')),
                ('knowledge_topics_choice', models.CharField(max_length=255, verbose_name='Areas de conocimiento de su elección')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de estudiantes',
            },
        ),
        migrations.CreateModel(
            name='StudyHostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('institution_type', models.CharField(choices=[('UNIVERSITY', 'Universidad'), ('TECH_SCHOOL', 'Escuela Tecnológica'), ('UNIV_INST', 'Institución Universitaria'), ('PROF_TECH_INST', 'Institución Tecnológica Profesional'), ('CONTINUAL_EDUCATION_CENTER', 'Centro de Educación Contínua')], max_length=255, verbose_name='Tipo de institución')),
                ('institute_character', models.CharField(choices=[('PRIVATE', 'Privada'), ('PUBLIC', 'Pública'), ('MIXED', 'Privada - Pública')], max_length=7, verbose_name='Caracter de la institución')),
                ('high_quality_accreditations', models.CharField(max_length=255, verbose_name='Acreditaciones de alta calidad')),
                ('students_number', models.CharField(choices=[('Less than a thousand students', 'Menos de 1.000 estudiantes'), ('Between one thousand and ten thousand students', 'Entre 1.000 y 10.000 estudiantes'), ('Between ten thousand and twenty thousand students', 'Entre 10.000 y 20.000 estudiantes'), ('More/Greater than twenty thousand students', 'Mayor a 20.000 estudiantes')], max_length=255, verbose_name='Número de estudiantes')),
                ('rankings_classification', models.CharField(max_length=255, verbose_name='Clasificación en ranking')),
                ('strengths', models.CharField(max_length=255, verbose_name='Fortalezas')),
                ('knowledge_topics', taggit.managers.TaggableManager(help_text='Una lista separada de temas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tópicos de conocimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios con perfil de anfitriones de estudio',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
