# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveprofile',
            name='complete_studies_school',
            field=models.CharField(max_length=255, verbose_name='Institución en donde terminó sus estudios anteriores'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='complete_studies_school',
            field=models.CharField(max_length=255, verbose_name='Institución en donde terminó sus estudios anteriores'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='current_education_school',
            field=models.CharField(max_length=128, verbose_name='Institución educativa en la cual está vinculado en su actual lugar residencia'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='educational_titles',
            field=models.CharField(max_length=255, verbose_name='Títulos educativos'),
        ),
    ]
