# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_information', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entertainment_activities',
            field=models.ManyToManyField(blank=True, to='host_information.EntertainmentActivities'),
        ),
        migrations.AddField(
            model_name='user',
            name='speak_languages',
            field=models.ManyToManyField(blank=True, help_text='What languages do you speak?', related_name='users', to='host_information.SpeakLanguages', verbose_name='Languages'),
        ),
    ]
