# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherServicesHostProfile',
            new_name='AyniHostProfile',
        ),
        migrations.RenameModel(
            old_name='EntertainmentHostProfile',
            new_name='DailyLifeHostProfile',
        ),
        migrations.RenameModel(
            old_name='InnovationHostProfile',
            new_name='EnterprenurshipHostProfile',
        ),
        migrations.AlterModelOptions(
            name='aynihostprofile',
            options={'verbose_name_plural': 'Usuarios con perfil de AYNI'},
        ),
        migrations.AlterModelOptions(
            name='dailylifehostprofile',
            options={'verbose_name_plural': 'Usuarios con perfil de anfitriones de servicios varios'},
        ),
        migrations.AlterModelOptions(
            name='enterprenurshiphostprofile',
            options={'verbose_name_plural': 'Usuarios con perfil de anfitriones de emprendimiento'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_entertainment_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_innovation_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_other_services_host',
        ),
        migrations.AddField(
            model_name='user',
            name='is_ayni_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrión AYNI'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_daily_life_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrión de servicios de vida diaria'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_entrepreneurship_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrión de emprendimiento'),
        ),
    ]
