# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-07 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180207_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_education_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Institución educativa en la cual está vinculado en su actual lugar residencia'),
        ),
    ]
