# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professorprofile_autorship_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyhostprofile',
            name='strengths',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_current_residence',
            field=models.CharField(max_length=255, verbose_name='Ciudad actual de residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_of_origin',
            field=models.CharField(max_length=255, verbose_name='Ciudad de origen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_current_residence',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='País actual de residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_origin',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Pais de origen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>MM-DD-YYYY</em>.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entertainment_activities',
            field=models.ManyToManyField(blank=True, help_text='Mantenga presionado "Control" o "Command" en un Mac, para seleccionar más de una opción.', to='host_information.EntertainmentActivities', verbose_name='Actividades de entretenimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_entertainment_host',
            field=models.BooleanField(default=False, help_text='Perfil de anfitrión de entretenimiento', verbose_name='Anfitrión de entretenimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False, help_text='Perfil de ejecutivo o emprendedor', verbose_name='Ejecutivo/Emprendedor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hosting_host',
            field=models.BooleanField(default=False, help_text='Perfil de anfitrión de hospedaje', verbose_name='Anfitrión de alojamiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_innovation_host',
            field=models.BooleanField(default=False, help_text='Perfil de anfitrión de innovación', verbose_name='Anfitrión de innovación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_other_services_host',
            field=models.BooleanField(default=False, help_text='Perfil de anfitrión de otros servicios', verbose_name='Anfitrión de otros servicios'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, help_text='Perfil de profesor', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Perfil de estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_study_host',
            field=models.BooleanField(default=False, help_text='Perfil de anfitrón académico', verbose_name='Anfitrion de estudio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Por favor use el siguiente formato: <em>+Country Code-Number</em>.', max_length=128, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='speak_languages',
            field=models.ManyToManyField(blank=True, help_text='Mantenga presionado "Control" o "Command" en un Mac, para seleccionar más de una opción.', related_name='users', to='host_information.SpeakLanguages', verbose_name='Idiomas'),
        ),
    ]
