# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-26 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180421_1542'),
        ('accounts', '0004_auto_20180421_1115'),
    ]

    operations = [
    ]
