# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170923_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=140, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entertainment_activities',
            field=models.ManyToManyField(blank=True, help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', to='host_information.EntertainmentActivities', verbose_name='Actividades de entretenimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='speak_languages',
            field=models.ManyToManyField(blank=True, help_text='Mantenga presionado "Control" (o "Command" en un Mac), y haga click en las opciones que desea selecionar.', related_name='users', to='host_information.SpeakLanguages', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('P', 'Persona'), ('O', 'Organización')], default=False, max_length=10, verbose_name='Tipo de Usuario'),
        ),
    ]
