# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20181026_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_executive',
            new_name='is_employed',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_professor',
            new_name='is_independent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_ayni_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_daily_life_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_entrepreneurship_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hosting_host',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_study_host',
        ),
        migrations.AlterField(
            model_name='studyhostprofile',
            name='institute_character',
            field=models.CharField(choices=[('PRIVATE', 'Privada'), ('PUBLIC', 'Pública')], max_length=7, verbose_name='Caracter de la institución'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=60, verbose_name='Nombre completo'),
        ),
    ]
