# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181026_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complete_studies_school',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución en donde completó sus estudios anteriores'),
        ),
        migrations.AddField(
            model_name='user',
            name='educational_titles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulos Educativos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employed',
            field=models.BooleanField(default=False, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_independent',
            field=models.BooleanField(default=False, verbose_name='Independiente'),
        ),
    ]
