# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170930_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_current_residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad actual de residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_of_origin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad de origen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_current_residence',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='País actual de residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Pais de origen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
