# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-30 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170930_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Biografía'),
        ),
    ]
