# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entertainment_activities',
        ),
        migrations.AddField(
            model_name='user',
            name='entrepreneurship_areas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Areas de emprendimiento'),
        ),
    ]
