# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 23:37
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170930_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='userprofile-pics/default_profile_pic.png', null=True, upload_to=accounts.models.get_image_path, verbose_name='Fotografía de perfil'),
        ),
    ]
