# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171001_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_and_conditions',
            field=models.BooleanField(default=False, help_text='Términos y Condiciones y Política de tratamiendo de datos', verbose_name='Terminos y Condiciones'),
        ),
    ]
