# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_terms_and_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='terms_and_conditions',
        ),
    ]
