# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 13:56
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Descripción de la empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_image_path, verbose_name='Fotografía de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>DD/MM/YYYY</em>.', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
