# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20171003_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(blank=True, help_text='Por favor use el formato: <em>DD/MM/YYYY</em>.', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
