# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171003_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(default=1, verbose_name='Biografía'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(blank=True, help_text='Por favor use el formato: <em>DD/MM/YYYY</em>.', null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripción de la empresa'),
            preserve_default=False,
        ),
    ]
