# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20171003_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_current_residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad de residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la organización'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Por favor use el siguiente formato: <em>+Country Code-Number</em>.', max_length=128, null=True, verbose_name='Número de contacto'),
        ),
    ]
