# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 15:13
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20171003_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='userprofile-pics/default_profile_pic.png', null=True, upload_to=accounts.models.get_image_path, verbose_name='Fotografía de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_current_residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad actual de residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Por favor use el formato: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='enterprise name'),
        ),
    ]
