# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 15:33
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_image_path, verbose_name='Fotografía de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_current_residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad de residencia'),
        ),
    ]
