# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20171003_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhostprofile',
            name='institution_type',
            field=models.CharField(choices=[('Universidad', 'Universidad'), ('Escuela Tecnológica', 'Escuela Tecnológica'), ('Institución Universitaria', 'Institución Universitaria'), ('Institución Tecnológica Profesiona', 'Institución Tecnológica Profesional'), ('Centro de Educación Contínua', 'Centro de Educación Contínua'), ('Centro de Educación Contínua', 'Centro de Educación para la vida y el trabajo')], max_length=255, verbose_name='Tipo de institución'),
        ),
        migrations.AlterField(
            model_name='studyhostprofile',
            name='rankings_classification',
            field=models.TextField(verbose_name='Clasificación en ranking'),
        ),
        migrations.AlterField(
            model_name='studyhostprofile',
            name='students_number',
            field=models.CharField(choices=[('Menos de 1.000 estudiantes', 'Menos de 1.000 estudiantes'), ('Entre 1.000 y 10.000 estudiantes', 'Entre 1.000 y 10.000 estudiantes'), ('Entre 10.000 y 20.000 estudiantes', 'Entre 10.000 y 20.000 estudiantes'), ('Mayor a 20.000 estudiantes', 'Mayor a 20.000 estudiantes')], max_length=255, verbose_name='Número de estudiantes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_current_residence',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='País de residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de la organización'),
        ),
    ]
