# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20171004_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_entertainment_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrión de entretenimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False, verbose_name='Ejecutivo/Emprendedor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hosting_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrión de alojamiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_innovation_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrión de innovación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_other_services_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrión de otros servicios'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_study_host',
            field=models.BooleanField(default=False, verbose_name='Anfitrion de estudio'),
        ),
    ]
