# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20171013_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinghostprofile',
            name='additional_description',
        ),
        migrations.AlterField(
            model_name='studyhostprofile',
            name='institution_type',
            field=models.CharField(choices=[('Universidad', 'Universidad'), ('Institución Universitaria', 'Institución Universitaria'), ('Institución Tecnológica Profesiona', 'Institución Técnica y/o Tecnológica '), ('Centro de Educación Contínua', 'Centro de Educación Contínua'), ('Centro de Educación Contínua', 'Centro de Educación para la vida y el trabajo')], max_length=255, verbose_name='Tipo de institución'),
        ),
        migrations.AlterField(
            model_name='studyhostprofile',
            name='knowledge_topics',
            field=taggit.managers.TaggableManager(help_text='Una lista separada de temas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Áreas de conocimiento'),
        ),
    ]
