# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-26 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181026_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=False, help_text='Si seleccionas esta  opción tu artículo no será publicado, solo guardado por el momento', verbose_name='Guardar publicación'),
        ),
    ]
