# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170926_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images', verbose_name='Image'),
        ),
    ]
