# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170927_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images', verbose_name='Image'),
        ),
    ]
