# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-28 04:36
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170927_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=blog.models.upload_location, width_field='width_field'),
        ),
    ]
