# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 23:37
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170930_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(height_field='height_field', help_text='La fotografía a publicarse, preferiblemente de ancho:1920 y de alto:1980', upload_to=blog.models.upload_location, verbose_name='Imagen', width_field='width_field'),
        ),
    ]
