# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20171001_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=False, help_text='Si seleccionas esta  opción tu artículo no será publicado por el momento', verbose_name='Borrador'),
        ),
    ]
