# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-13 15:51
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171002_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(height_field='height_field', help_text='El tamaño de la imagen debe ser de 1080 por 920', upload_to=blog.models.upload_location, verbose_name='Imagen', width_field='width_field'),
        ),
    ]
