# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-16 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostayni', '0003_slider_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
