# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import hostayni.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostayni', '0005_auto_20180217_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=False, help_text='Indica si el anuncio estara activo o no en la pagina de inicio en hostayni'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='end_date',
            field=models.DateField(blank=True, help_text='Indica hasta que fecha el anuncio estara en la pagina de inicio de hostayni', null=True, verbose_name='Fecha de finalizacion del anuncio'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='header_text',
            field=models.CharField(blank=True, help_text='Opcional', max_length=120, null=True, verbose_name='Ingrese un encabezado para el banner'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=hostayni.models.slider_upload, verbose_name='Imagen a aparecer en el carrusel'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, help_text='Ingrese un numero', verbose_name='Ingrese el orden en que desea que aparezca la imagen'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='start_date',
            field=models.DateField(blank=True, help_text='Indica desde que fecha el anuncio empezara a aparecer en la pagina de inicio de hostayni', null=True, verbose_name='Fecha de inicio del anuncio'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.CharField(blank=True, help_text='Opcional', max_length=120, null=True, verbose_name='Ingrese un caption para el banner'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Ingrese el nombre de quien pauta'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url_link',
            field=models.CharField(blank=True, help_text='Opcional', max_length=250, null=True, verbose_name='Ingrese un enlace promocional'),
        ),
    ]
