# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 01:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import entrepreneurship.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurshipOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ad_title', models.CharField(max_length=255, verbose_name='Título de la oferta')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('offer_type', models.CharField(choices=[('Formación o Mentorías', 'Formación o Mentorías'), ('Convocatoria para emprendedores o empresarios', 'Convocatoria para emprendedores o empresarios'), ('Voluntariados', 'Voluntariados')], max_length=20, verbose_name='Tipo de oferta')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pais')),
                ('city', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('date', models.DateField(blank=True, help_text='Ingresar aquí la fecha del evento, inicio del curso o voluntariado', null=True, verbose_name='Fecha del evento')),
                ('url', models.TextField(help_text='Para mayor información referencie una dirección o enlace web', validators=[django.core.validators.URLValidator()], verbose_name='Dirección de enlace')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nombre de contacto')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Por favor use el siguiente formato: <em>+Country Code-Number</em>.', max_length=128, verbose_name='Número telefónico de contacto')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Ingrese una dirección de correo válida.', 'Precaución')], verbose_name='Correo electrónico de contacto')),
                ('photo', models.ImageField(help_text='Esta imagen acompañará tu oferta en los resultados de búsquedas', upload_to=entrepreneurship.models.get_entrepreneurship_image_path, verbose_name='Fotografía')),
                ('is_taked', models.BooleanField(default=False, verbose_name='Oferta tomada')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Oferta promovida')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
