# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import entrepreneurship.models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurshipOfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=entrepreneurship.models.get_image_filename, verbose_name='Imagen')),
            ],
        ),
        migrations.AlterModelOptions(
            name='entrepreneurshipoffer',
            options={'ordering': ['-is_paid', '-created', '-modified']},
        ),
        migrations.AddField(
            model_name='entrepreneurshipoffer',
            name='price',
            field=models.CharField(default=1, help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio mensual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrepreneurshipofferimage',
            name='entrepreneurship_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneurshipofferimage', to='entrepreneurship.EntrepreneurshipOffer'),
        ),
    ]
