# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de contacto'),
        ),
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico de contacto'),
        ),
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Por favor use el siguiente formato: <em>+Country Code-Number</em>.', max_length=128, null=True, verbose_name='Número telefónico de contacto'),
        ),
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='price',
            field=models.CharField(blank=True, help_text='Precio en pesos colombianos', max_length=128, null=True, verbose_name='Precio'),
        ),
    ]
