# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0002_auto_20180326_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='offer_type',
            field=models.CharField(choices=[('Formación o Mentorías', 'Formación o Mentorías'), ('Convocatoria para emprendedores o empresarios', 'Convocatoria para emprendedores o empresarios'), ('Voluntariados', 'Voluntariados')], max_length=100, verbose_name='Tipo de oferta'),
        ),
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='price',
            field=models.CharField(help_text='Precio en pesos colombianos', max_length=128, verbose_name='Precio'),
        ),
    ]
