# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-28 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0003_auto_20181026_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='status',
            field=models.CharField(choices=[('Cupos disponibles', 'Cupos disponibles'), ('Voluntariados', 'Cupos agotados'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default=False, max_length=10, verbose_name='Estado'),
        ),
    ]
