# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 13:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0003_auto_20180326_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurshipoffer',
            name='url',
            field=models.TextField(help_text='Para mayor información referencie una dirección o enlace web', null=True, validators=[django.core.validators.URLValidator()], verbose_name='Dirección de enlace'),
        ),
    ]
